                   THE WEBSITE IS DESIGNED, DEVELOPED and HOSTED BY BIT KANPUR STUDENTS.
                 DISCLAIMER: EVERY EFFORT HAS BEEN MADE TO ENSURE ACCURACY OF DATA ON THIS WEB SITE.
                 WE WILL NOT BE RESPONSIBLE FOR ANY DECISION OR CLAIM THAT IS BASED ON THE DISPLAYED DATA. 
                 THE SLIDER IMAGES HAVE BEEN TAKEN FROM GOOGLE.WHILE USING THIS SITE, YOU AGREE TO HAVE
                  READ AND ACCEPTED OUR TERMS OF USE, COOKIE AND PRIVACY POLICY.
                <br> COPYRIGHT <i class="fa fa-copyright"> </i> 2005-2018 BY MY CITY SEARCH.
                  ALL RIGHTS RESERVED <i class="fa fa-registered"></i>.